language: clojure
lein: 2.8.3
dist: xenial
services:
  - docker
jdk:
  - openjdk8
jobs:
  include:
    - name: "Legacy Grafana"
      env: GRAFANA_TEST_VERSION=${GRAFANA_TEST_VERSION_LEGACY}
    - name: "Latest Grafana"
      env: GRAFANA_TEST_VERSION=${GRAFANA_TEST_VERSION_LATEST}
before_install:
  - docker run --rm -d -p ${GRAFANA_TEST_PORT}:3000 -v "$(pwd)/grafana/datasources":/etc/grafana/provisioning/datasources -v "$(pwd)/grafana/dashboards":/etc/grafana/provisioning/dashboards grafana/grafana:${GRAFANA_TEST_VERSION}
script: lein do cljfmt check, eastwood, test :all
deploy:
  provider: script
  skip_cleanup: true
  script: lein deploy
  on:
    tags: true
cache:
  directories:
    - $HOME/.m2
