language: clojure
lein: 2.8.3
dist: xenial
services:
  - docker
jdk:
  - openjdk8    
env:
  matrix:
    - GRAFANA_TEST_VERSION=6.2.5 GRAFANA_TEST_URI=http://localhost:3000 GRAFANA_TEST_PORT=3000
    - GRAFANA_TEST_VERSION=6.6.0 GRAFANA_TEST_URI=http://localhost:3001 GRAFANA_TEST_PORT=3001
before_install:
  - docker run --rm -d -p ${GRAFANA_TEST_PORT}:3000 -v "$(pwd)/grafana/datasources":/etc/grafana/provisioning/datasources -v "$(pwd)/grafana/dashboards":/etc/grafana/provisioning/dashboards grafana/grafana:${GRAFANA_TEST_VERSION}
script: lein do cljfmt check, eastwood, test :all
deploy:
  provider: script
  skip_cleanup: true
  script: lein deploy
  on:
    tags: true
cache:
  directories:
    - $HOME/.m2
